
const MONGO_USER = process.env.MONGO_USER,
  MONGO_PASSWORD = process.env.MONGO_PASSWORD,
  MONGO_URL = process.env.MONGO_URL,
  MONGO_DATABASE = process.env.MONGO_DATABASE,
  JWT_KEY = process.env.JWT_KEY;

module.exports = {
  MONGO_USER: MONGO_USER,
  MONGO_PASSWORD: MONGO_PASSWORD,
  MONGO_URL: MONGO_URL,
  MONGO_DATABASE: MONGO_DATABASE,
  JWT_KEY: JWT_KEY,
};
